[package]
name = "xx_hash-sys"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
libc = { version = "0.2.155", default-features = false }
paste = { version = "1.0.15", default-features = false }

[build-dependencies]
cc = { version = "1.1.6", default-features = false }
