language: rust
sudo: false
rust:
  - 1.7.0
  - stable
  - beta
  - nightly
matrix:
  include:
  - rust: nightly
    env: FEATURES="unstable"
script: |
  cargo build --verbose --features "${FEATURES}"
  cargo test --verbose --features "${FEATURES}"
