[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "comparison"
version = "0.1.0"

[dependencies]
fnv = "1.0"
quickcheck = "0.4.1"
rand = "0.3.15"
twox-hash = { path = ".." }
libc = "0.2.53"

[features]
bench = []

[build-dependencies]
cc = "1.0.36"
